#!/usr/bin/env php
<?php
/**
 * This file is part of the PPI Framework.
 *
 * @category    PPI
 * @package     DistributionModule
 * @copyright   Copyright (c) 2011-2013 Paul Dragoonis <paul@ppi.io>
 * @license     http://opensource.org/licenses/mit-license.php MIT
 * @link        http://www.ppi.io
 */

set_time_limit(0);

require_once 'init.php';

$config = include 'config/app.php';

use PPI\Console\Command\ModuleCommand;

$application = new Application();
$application->add(new ModuleCommand(array(
    'skeleton.module.path' => $config['skeleton.module.path']
)));
$application->run();
