#!/usr/bin/env php
<?php
/**
 * This file is part of the PPI Framework.
 *
 * @category    PPI
 * @package     DistributionModule
 * @copyright   Copyright (c) 2011-2014 Paul Dragoonis <paul@ppi.io>
 * @license     http://opensource.org/licenses/mit-license.php MIT
 * @link        http://www.ppi.io
 */

set_time_limit(0);

chdir(dirname(__DIR__));
require_once __DIR__ . '/init.php';

use PPI\Framework\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('PPI_ENV') ?: 'dev');
$debug = getenv('PPI_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$app = new PPI\Framework\App(array(
    'environment'   => $env,
    'debug'         => $debug,
    'rootDir'       => __DIR__
));
$app->loadConfig($app->getEnvironment().'/app.php');

$application = new Application($app);
$application->run();
