#!/usr/bin/env php
<?php
/**
 * This file is part of the PPI Framework.
 *
 * @category    PPI
 * @package     DistributionModule
 * @copyright   Copyright (c) 2011-2014 Paul Dragoonis <paul@ppi.io>
 * @license     http://opensource.org/licenses/mit-license.php MIT
 * @link        http://www.ppi.io
 */

set_time_limit(0);

chdir(dirname(__DIR__));
require_once __DIR__ . '/init.php';

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Bundle\FrameworkBundle\Console\Application;

$input = new ArgvInput();
$output = new ConsoleOutput();

$env = $input->getParameterOption(array('--env', '-e'), getenv('PPI_ENV') ?: 'dev');
$debug = getenv('PPI_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$sfKernel = include 'symfony.php';

$application = new Application($sfKernel);
$application->doRun($input, $output);
