#imports:
#    - { resource: "symfony/security.yml" }

framework:
    secret: mysecret
    router:
        resource: '%kernel.root_dir%/config/dev/symfony_routing.yml'

    templating:
        engines: ['twig']

nelmio_api_doc:

    swagger:
        api_base_path:        /api
        swagger_version:      '1.2'
        api_version:          '0.1'
        info:
            title:                Symfony2
            description:          'My awesome Symfony2 app!'
            TermsOfServiceUrl:    null
            contact:              null
            license:              null
            licenseUrl:           null