bundles:
  - Symfony\Bundle\FrameworkBundle\FrameworkBundle
  - Symfony\Bundle\SecurityBundle\SecurityBundle
  - Symfony\Bundle\TwigBundle\TwigBundle
  - Nelmio\ApiDocBundle\NelmioApiDocBundle
  - TestBundle\TestBundle
  - Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
  - Doctrine\Bundle\DoctrineBundle\DoctrineBundle
  - FOS\UserBundle\FOSUserBundle
