fields:
	email:
		type: text
		label: Email
		size: 30
	password:
		type: password
		label: Password
		size: 30
	submit:
		type: submit
		label: Login
		value: Login
rules:
	email:
		type: required
		message: Email cannot be blank
	password:
		type: required
		message: Password cannot be blank